### ISSUE TITLE
话说能加入你们一起做podcast吗？

### ISSUE THREAD

**Issue by origamidance** [TechMoron/Podcasts#1]

**Comment by li-xinyang** [comment]
暂时没有打算加入更多的人参与到制作过程中来，而且我们也是第一次制作博客节目。具体还有有什么问题可以在这里留言或者写邮件给我 techmoron@yahoo.com 。

**Comment by origamidance** [comment]
IT公论停播和内核恐慌长期不更以后，我就也想做一个技术播客啥的，后来问了好多人也都没找到愿意花时间一起做的，所以看到你们这个就想问问。。。

**Comment by li-xinyang** [comment]
我们的水平和可以投入的时间都可能和你想想的不想一样，所以你可以听到节目之后再决定是否要参与进来。暂时没有计划加入更多的人，尽量把各种因素控制在可控范围之内。

我们是非盈利节目，也不准备做盈利的方式，所以这也会导致更新频率和节目质量之间会有权衡。
